{
  pkgs,
  pname,
  flake,
}:
let
  inherit (pkgs) lib;

  palette = import ./palette.nix;

  fonts = {
    # Pixel font for all shell text; drawn on an 11px grid.
    ui = {
      name = "Departure Mono";
      package = pkgs.departure-mono;
    };
    # DIN 1451 condensed for mastheads and big readouts.
    display = {
      name = "DINish Condensed";
      package = pkgs.dinish;
    };
  };

  wallpaper = builtins.path {
    path = flake + "/assets/wallpaper-ariane.png";
    name = "wallpaper-ariane.png";
  };

  # The source is 6400x3600 and PNG can't be decoded at a smaller size, so the
  # desktop would decode all of it on every start just to scale it down.
  desktopWallpaper =
    pkgs.runCommand "signalis-wallpaper.png" { nativeBuildInputs = [ pkgs.imagemagick ]; }
      ''
        magick ${wallpaper} -resize '3840x>' -strip $out
      '';

  # The lock screen shows the wallpaper at 12%; bake that in at a sane size so
  # it decodes in the same frame the lock appears.
  lockWallpaper =
    pkgs.runCommand "signalis-lock-wallpaper.png" { nativeBuildInputs = [ pkgs.imagemagick ]; }
      ''
        magick ${wallpaper} -resize 3200x -fill black -colorize 88% -strip $out
      '';

  colorProps = lib.concatStrings (
    lib.mapAttrsToList
      (name: value: ''
        readonly property color ${name}: "${value}"
      '')
      (
        removeAttrs palette [
          "raw"
          "base16"
        ]
      )
  );

  theme = pkgs.writeText "Theme.qml" ''
    pragma Singleton
    import QtQuick
    import Quickshell

    // Generated by packages/signalis-shell from palette.nix.
    Singleton {
    ${colorProps}
      readonly property string fontUi: "${fonts.ui.name}"
      readonly property string fontDisplay: "${fonts.display.name}"
      readonly property string wallpaper: "file://${desktopWallpaper}"
      readonly property string lockWallpaper: "file://${lockWallpaper}"

      function alpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a);
      }
    }
  '';

  # The anyrun package builds its plugins and then drops the shared libraries.
  # The provider and these libraries share one anyrun-interface revision.
  anyrunWithPlugins = pkgs.anyrun.overrideAttrs (old: {
    postInstall = old.postInstall + ''
      mkdir -p $out/lib
      for lib in libapplications.so librink.so libshell.so libwebsearch.so; do
        path=$(find target -type f -name "$lib" -print -quit)
        if [ -z "$path" ]; then
          echo "anyrun plugin $lib was not built" >&2
          find target -name '*.so' >&2 || true
          exit 1
        fi
        cp -f "$path" $out/lib/
      done
    '';
  });

  anyrunPlugins = lib.concatStringsSep ":" (
    map (name: "${anyrunWithPlugins}/lib/lib${name}.so") [
      "applications"
      "rink"
      "shell"
      "websearch"
    ]
  );

  anyrunConfig = pkgs.runCommand "signalis-anyrun-config" { } ''
    mkdir -p $out
    cp ${./anyrun}/applications.ron $out/applications.ron
    cp ${./anyrun}/rink.ron $out/rink.ron
    cp ${./anyrun}/shell.ron $out/shell.ron
    cp ${./anyrun}/websearch.ron $out/websearch.ron
  '';

  # Writes one line to a unix socket. Mod+X uses this instead of starting quickshell.
  signalis-poke = pkgs.runCommandCC "signalis-poke" { } ''
    mkdir -p $out/bin
    $CC -O2 -o $out/bin/signalis-poke ${./signalis-poke.c}
  '';

  runtimePath = lib.makeBinPath (
    with pkgs;
    [
      brightnessctl
      wireplumber
      systemd
      glib
      xdg-utils
      coreutils
      iproute2
      iw
      gawk
      networkmanager
      wl-clipboard
      bash
    ]
  );

  quickshell = lib.getExe pkgs.quickshell;
in
pkgs.stdenvNoCC.mkDerivation (finalAttrs: {
  inherit pname;
  version = "0.1.0";

  src = ./qml;

  nativeBuildInputs = [ pkgs.makeWrapper ];

  installPhase = ''
    runHook preInstall

    share=$out/share/${pname}
    mkdir -p $share $out/bin
    cp -r . $share
    install -Dm644 ${theme} $share/config/Theme.qml

    for entry in shell lock greeter; do
      makeWrapper ${quickshell} $out/bin/signalis-$entry \
        --prefix PATH : $out/bin:${runtimePath} \
        --set SIGNALIS_ANYRUN_PROVIDER ${lib.getExe pkgs.anyrun-provider} \
        --set SIGNALIS_ANYRUN_PLUGINS ${anyrunPlugins} \
        --set SIGNALIS_ANYRUN_CONFIG ${anyrunConfig} \
        --add-flags "-p $share/$entry.qml"
    done

    # IPC into the running instances, e.g. `signalis-ctl lock` or `signalis-ctl launcher toggle`.
    # The launcher socket is served by the shell. The quickshell client is the fallback.
    cat > $out/bin/signalis-ctl <<EOF
    #!${pkgs.runtimeShell}
    case "\$1" in
      lock) exec ${quickshell} -p $share/lock.qml ipc call lock lock ;;
      power-key) exec ${quickshell} -p $share/lock.qml ipc call lock powerKey ;;
      launcher)
        if [ "\$2" = toggle ] && [ -n "\$XDG_RUNTIME_DIR" ] \
          && ${signalis-poke}/bin/signalis-poke "\$XDG_RUNTIME_DIR/signalis-launcher.sock" toggle
        then
          exit 0
        fi
        exec ${quickshell} -p $share/shell.qml ipc call "\$@"
        ;;
      *) exec ${quickshell} -p $share/shell.qml ipc call "\$@" ;;
    esac
    EOF
    chmod +x $out/bin/signalis-ctl

    runHook postInstall
  '';

  passthru = {
    inherit palette fonts wallpaper;

    # niri config for greetd: a throwaway compositor that runs the greeter and
    # quits once it has launched the session. Validated with `niri validate`.
    mkGreeterConfig =
      {
        niri,
        user,
        session,
        xkb ? { },
        outputs ? { },
        cursor ? null,
      }:
      let
        str = builtins.toJSON;
        output =
          name: value:
          lib.optionalString ((value.scale or null) != null) ''
            output ${str name} {
                scale ${toString value.scale}
            }
          '';
      in
      pkgs.runCommand "signalis-greeter-niri.kdl"
        {
          nativeBuildInputs = [ niri ];
          passAsFile = [ "text" ];
          text = ''
            hotkey-overlay {
                skip-at-startup
            }
            prefer-no-csd
            input {
                keyboard {
                    xkb {
                        ${lib.optionalString (xkb ? layout) "layout ${str xkb.layout}"}
                        ${lib.optionalString (xkb ? options) "options ${str xkb.options}"}
                    }
                }
                touchpad {
                    tap
                    natural-scroll
                }
            }
            ${lib.concatStrings (lib.mapAttrsToList output outputs)}
            // Hidden from the first frame: nothing on the black before the greeter maps.
            cursor {
                hide-after-inactive-ms 0
                ${lib.optionalString (cursor != null) ''
                  xcursor-theme ${str cursor.name}
                  xcursor-size ${toString cursor.size}
                ''}
            }
            layout {
                background-color ${str palette.bg}
            }
            environment {
                SIGNALIS_USER ${str user}
                SIGNALIS_SESSION ${str session}
            }
            spawn-sh-at-startup "${finalAttrs.finalPackage}/bin/signalis-greeter; niri msg action quit --skip-confirmation"
          '';
        }
        ''
          cp "$textPath" $out
          niri validate --config $out
        '';
  };

  meta = {
    description = "Signalis-style desktop shell for niri: bar, launcher, notifications, lock and greeter";
    platforms = lib.platforms.linux;
    mainProgram = "signalis-shell";
  };
})
