{
  pkgs,
  pname,
  flake,
}:
let
  inherit (pkgs) lib;

  palette = import ./palette.nix;

  fonts = {
    # Pixel font for all shell text; drawn on an 11px grid.
    ui = {
      name = "Departure Mono";
      package = pkgs.departure-mono;
    };
    # DIN 1451 condensed for mastheads and big readouts.
    display = {
      name = "DINish Condensed";
      package = pkgs.dinish;
    };
  };

  wallpaper = flake + "/assets/wallpaper-ariane.png";

  # The lock screen shows the wallpaper at 12%; bake that in at a sane size so
  # it decodes in the same frame the lock appears.
  lockWallpaper =
    pkgs.runCommand "signalis-lock-wallpaper.png" { nativeBuildInputs = [ pkgs.imagemagick ]; }
      ''
        magick ${wallpaper} -resize 3200x -fill black -colorize 88% -strip $out
      '';

  colorProps = lib.concatStrings (
    lib.mapAttrsToList
      (name: value: ''
        readonly property color ${name}: "${value}"
      '')
      (
        removeAttrs palette [
          "raw"
          "base16"
        ]
      )
  );

  theme = pkgs.writeText "Theme.qml" ''
    pragma Singleton
    import QtQuick
    import Quickshell

    // Generated by packages/signalis-shell from palette.nix.
    Singleton {
    ${colorProps}
      readonly property string fontUi: "${fonts.ui.name}"
      readonly property string fontDisplay: "${fonts.display.name}"
      readonly property string wallpaper: "file://${wallpaper}"
      readonly property string lockWallpaper: "file://${lockWallpaper}"

      function alpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a);
      }
    }
  '';

  runtimePath = lib.makeBinPath (
    with pkgs;
    [
      brightnessctl
      wireplumber
      systemd
      glib
      coreutils
      iproute2
      iw
      gawk
      networkmanager
    ]
  );

  quickshell = lib.getExe pkgs.quickshell;
in
pkgs.stdenvNoCC.mkDerivation (finalAttrs: {
  inherit pname;
  version = "0.1.0";

  src = ./qml;

  nativeBuildInputs = [ pkgs.makeWrapper ];

  installPhase = ''
    runHook preInstall

    share=$out/share/${pname}
    mkdir -p $share $out/bin
    cp -r . $share
    install -Dm644 ${theme} $share/config/Theme.qml

    for entry in shell lock greeter; do
      makeWrapper ${quickshell} $out/bin/signalis-$entry \
        --prefix PATH : $out/bin:${runtimePath} \
        --add-flags "-p $share/$entry.qml"
    done

    # IPC into the running instances, e.g. `signalis-ctl lock` or `signalis-ctl launcher toggle`.
    cat > $out/bin/signalis-ctl <<EOF
    #!${pkgs.runtimeShell}
    case "\$1" in
      lock) exec ${quickshell} -p $share/lock.qml ipc call lock lock ;;
      *) exec ${quickshell} -p $share/shell.qml ipc call "\$@" ;;
    esac
    EOF
    chmod +x $out/bin/signalis-ctl

    runHook postInstall
  '';

  passthru = {
    inherit palette fonts wallpaper;

    # niri config for greetd: a throwaway compositor that runs the greeter and
    # quits once it has launched the session. Validated with `niri validate`.
    mkGreeterConfig =
      {
        niri,
        user,
        session,
        xkb ? { },
        outputs ? { },
        cursor ? null,
      }:
      let
        str = builtins.toJSON;
        output =
          name: value:
          lib.optionalString ((value.scale or null) != null) ''
            output ${str name} {
                scale ${toString value.scale}
            }
          '';
      in
      pkgs.runCommand "signalis-greeter-niri.kdl"
        {
          nativeBuildInputs = [ niri ];
          passAsFile = [ "text" ];
          text = ''
            hotkey-overlay {
                skip-at-startup
            }
            prefer-no-csd
            input {
                keyboard {
                    xkb {
                        ${lib.optionalString (xkb ? layout) "layout ${str xkb.layout}"}
                        ${lib.optionalString (xkb ? options) "options ${str xkb.options}"}
                    }
                }
                touchpad {
                    tap
                    natural-scroll
                }
            }
            ${lib.concatStrings (lib.mapAttrsToList output outputs)}
            ${lib.optionalString (cursor != null) ''
              cursor {
                  xcursor-theme ${str cursor.name}
                  xcursor-size ${toString cursor.size}
              }
            ''}
            layout {
                background-color ${str palette.bg}
            }
            environment {
                SIGNALIS_USER ${str user}
                SIGNALIS_SESSION ${str session}
            }
            spawn-sh-at-startup "${finalAttrs.finalPackage}/bin/signalis-greeter; niri msg action quit --skip-confirmation"
          '';
        }
        ''
          cp "$textPath" $out
          niri validate --config $out
        '';
  };

  meta = {
    description = "Signalis-style desktop shell for niri: bar, launcher, notifications, lock and greeter";
    platforms = lib.platforms.linux;
    mainProgram = "signalis-shell";
  };
})
